### ISSUE TITLE
support pep621

### ISSUE THREAD

**Issue by graingert** [zestsoftware/zest.releaser#373]
pep621 is now publicly supported and documented in flit, zest.releaser should support it also by setting the pyproject.toml :

```toml
[project]
version = "0.0.0a0"
```
field

(While preserving quote type too)
